### PR TITLE
Dialer: Add option to disable proximity sensor

### PR DESCRIPTION
**Pull request by raystef66**
Provide a switch for end user to disable proximity sensor
while calling/incall.

### CODE REVIEW

**Comment by neobuddy89** [comment]
Isn't there config overlay present to disable it?

**Comment by raystef66** [comment]
Afaik this is the only way to disable proximity **only when calling**. Afaik other config overlays are just related to doze, present on incall etc. 
Since proximity sensor on F3 (and some other known xiaomi's) are useless when calling (false touches..) this commit is the only one that suits calls in combination with some macro/task I made.

**Comment by neobuddy89** [comment]
If you require to add on device and it should be permanently on, this can be device config overlay instead switch?

**Comment by raystef66** [comment]
Not requiring this as permanent on device since some users may need proximity for some other apps as well. 
Just want this to be working only when incall so this suits me fine.

**Review by neobuddy89 — APPROVED** [review]

**Pull request merged**
